### ISSUE TITLE
MainFragment OnPostExecute result = null

### ISSUE THREAD

**Issue by ConejoSama** [kanoka42/Steam-Integration-For-Android#1]
I tried to access steam using this integration. The access works but then when accessing MainFragment crashes

ERROR:

`
java.lang.NullPointerException: println needs a message
        at android.util.Log.println_native(Native Method)
        at android.util.Log.e(Log.java:334)
        at destryamiott.com.steamtestlogin.MainFragment$PostDataTask.onPostExecute(MainFragment.java:216)
        at destryamiott.com.steamtestlogin.MainFragment$PostDataTask.onPostExecute(MainFragment.java:152)
        at android.os.AsyncTask.finish(AsyncTask.java:651)
        at android.os.AsyncTask.access$500(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`
here's the code:

`
   @Override
        protected void onPostExecute(String result) {
            try {
                Log.e("Result: ", result);

                JSONObject jsonObject = new JSONObject(result);

                JSONObject response = jsonObject.getJSONObject("response");
                JSONArray jsonArray = response.getJSONArray("players");

                for(int i = 0; i < jsonArray.length(); i++){
                    JSONObject profile = jsonArray.getJSONObject(i);
                    String steamName = profile.getString("personaname");
                    profileName.setText(steamName);

                    imageUrl = profile.getString("avatarfull");

                    new DownloadImage().execute(imageUrl);
                }

            } catch (JSONException e){
                Log.e("JSON EXCEPTION ", e.toString());
            }

            super.onPostExecute(result);

            if (progressDialog != null){
                progressDialog.dismiss();
            }

        }
`
the string result retrieves null

PD: i've changed to on accessing to MainActivity it retrieves to LoginFragment instead of  MainFragment

`
  LoginFragment fragment = new LoginFragment();

        android.support.v4.app.FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();

        fragmentTransaction.replace(R.id.fragment_container, fragment);
        fragmentTransaction.commit();
`

any idea?

**Comment by kanoka42** [comment]
Have you tried commenting out the line 216 that throws the error? It's just a println, but if it's returning null then the whole onPostExecute is gonna throw probably. 

The only thing I can think of at the moment is that:
    1.) The steam url changed
    2.) There is no API key in the main fragment where there should be, it's all of the Xxxx's or
    3.) There was a problem logging in.

I have not compiled this code in around 3 years, so I will need some time tomorrow to compile and fix the issue.

**Comment by ConejoSama** [comment]
> Have you tried commenting out the line 216 that throws the error? It's just a println, but if it's returning null then the whole onPostExecute is gonna throw probably.
> 
> The only thing I can think of at the moment is that:
> 1.) The steam url changed
> 2.) There is no API key in the main fragment where there should be, it's all of the Xxxx's or
> 3.) There was a problem logging in.
> 
> I have not compiled this code in around 3 years, so I will need some time tomorrow to compile and fix the issue.

Thank you very much, I have solved it, there were 2 problems, the key was wrong and then the phone had an error, I solved it, thanks ^^
